# Basic Information
title: Sanaz Rabinia
position: Ph.D. in Computer Science
affiliation: AT&T Chief Data Office

# GitHub Pages project site
url: "https://sanazrabinia1.github.io"
baseurl: "/website"

# Search Engine Optimization (SEO)
keywords: "Sanaz Rabinia, computer science, edge computing, cloud computing, algorithms, machine learning, artificial intelligence, GPU, Wayne State University"
description: "Personal academic and professional website of Sanaz Rabinia, Ph.D. in Computer Science, specializing in algorithms, edge computing, cloud computing, combinatorial optimization, and applied machine learning/AI."
canonical: "https://sanazrabinia1.github.io/website/"

# Links
google_scholar: https://scholar.google.com/citations?user=VWis3OkAAAAJ&hl=en
cv_link: assets/files/curriculum_vitae.pdf
github_link: https://github.com/SanazRabinia1
linkedin: https://www.linkedin.com/in/sanaz-rabinia/

# Images
avatar: ./assets/img/Sanaz.jpeg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

enable_footnote: true
auto_dark_mode: false
font: "Serif"

remote_theme: yaoyao-liu/minimal-light

plugins:
  - jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
